"""The Workstream model: a directory of objective + snapshot + iterations.

Owns the deterministic control logic for the loop. After P5, state.json is the
source of truth for workstream status and iterations; markdown files are views
regenerated by the engine. The Clock is injected so the `opened` date is
deterministic and tests need no real wall-clock.
"""
from __future__ import annotations

from pathlib import Path

import json

from . import state
from .clock import Clock
from .errors import GateError
from .iteration import (
    DEFAULT_TYPE,
    Iteration,
    OPENABLE_AFTER,
    SKELETONS,
    TRANSITIONS,
    TYPES,
    VERDICT_LABELS,
    parse_dod_items,
    render_iter_md,
)
from .plan import PlanItem, render_plan
from .snapshot import build_snapshot

# Lifecycle state of a whole workstream, held in state.json (view: objective.md).
ACTIVE = "active"
CLOSED = "closed"


class Workstream:
    def __init__(self, path: Path, clock: Clock, state_doc: dict) -> None:
        self._path = path
        self._clock = clock
        self._state = state_doc

    @property
    def name(self) -> str:
        return self._path.name

    @property
    def state_doc(self) -> dict:
        """The in-memory state document. Read-only by convention."""
        return self._state

    @property
    def iterations_dir(self) -> Path:
        return self._path / "iterations"

    @property
    def objective_path(self) -> Path:
        return self._path / "objective.json"

    @property
    def status(self) -> str:
        """`active` or `closed`. Read from state.json."""
        return self._state["workstream"].get("status", ACTIVE)

    @property
    def is_closed(self) -> bool:
        return self.status == CLOSED

    def _load_objective(self) -> dict:
        from .validate import validate_entity
        path = self._path / "objective.json"
        import json
        doc = json.loads(path.read_text())
        validate_entity("objective", doc)
        return doc

    def _save_objective(self, doc: dict) -> None:
        from .validate import validate_entity
        import json
        validate_entity("objective", doc)
        (self._path / "objective.json").write_text(
            json.dumps(doc, indent=2, sort_keys=True) + "\n"
        )

    def _render_objective(self, doc: dict) -> None:
        """Regenerate objective.md as a derived view from an objective doc."""
        lines = [
            f"---",
            f"slug: {doc['slug']}",
            f"status: {doc['status']}",
            f"---",
            f"# {doc['title']}",
            f"",
            doc.get("text", ""),
        ]
        if doc.get("done_when"):
            lines += ["", f"Done-when: {doc['done_when']}"]
        (self._path / "objective.md").write_text("\n".join(lines).rstrip() + "\n")

    def set_status(self, status: str) -> None:
        """Update workstream status in state.json and objective.json, regenerate view."""
        self._state["workstream"]["status"] = status
        self._save_state()
        obj = self._load_objective()
        obj["status"] = status
        self._save_objective(obj)
        self._render_objective(obj)

    def objective_line(self) -> str:
        """Workstream title from state — no disk read required."""
        return self._state["workstream"].get("title", "(empty objective)")

    def snapshot_done_now_next(self) -> str:
        """Verbatim slice of snapshot.md from the first `## Done` to EOF."""
        snap = self._path / "snapshot.md"
        if not snap.is_file():
            return "(no snapshot)"
        lines = snap.read_text().splitlines()
        for i, line in enumerate(lines):
            if line.strip().lower().startswith("## done"):
                return "\n".join(lines[i:]).rstrip()
        return snap.read_text().rstrip()

    def iteration_ids(self) -> list[int]:
        return [e["id"] for e in self._state["iterations"]]

    def iterations(self) -> list[Iteration]:
        """Every iteration, oldest first — built from state.json."""
        return [Iteration.from_entity(e) for e in self._state["iterations"]]

    def current_iteration(self) -> Iteration | None:
        if not self._state["iterations"]:
            return None
        return Iteration.from_entity(self._state["iterations"][-1])

    def plan_items(self) -> list[PlanItem] | None:
        """Plan items from state.json.

        Returns None when state.plan is empty — signals build_snapshot to
        preserve the hand-authored Next section rather than derive one.
        Returns a non-empty list when plan items exist.
        """
        items = self._state.get("plan", [])
        if not items:
            return None
        return [PlanItem.from_entity(e) for e in items]

    def _render_plan(self) -> None:
        """Regenerate plan.md as a derived view from state.plan.

        No-op when there are no plan items — avoids creating a plan.md where
        none existed before.
        """
        items = self.plan_items()
        if items is None:
            return
        (self._path / "plan.md").write_text(render_plan(items, self.name))

    def _save_state(self) -> None:
        """Validate + save state.json, then regenerate plan.md view."""
        state.save(self._path / state.STATE_FILE, self._state)
        self._render_plan()

    def _load_iter_content(self, iter_id: int) -> dict:
        from .validate import validate_entity
        doc = json.loads((self.iterations_dir / f"{iter_id:03d}.json").read_text())
        validate_entity("iteration_content", doc)
        return doc

    def _save_iter_content(self, iter_id: int, content: dict) -> None:
        from .validate import validate_entity
        validate_entity("iteration_content", content)
        (self.iterations_dir / f"{iter_id:03d}.json").write_text(
            json.dumps(content, indent=2, sort_keys=True) + "\n"
        )

    def _render_iter(self, entity: dict, content: dict) -> None:
        (self.iterations_dir / f"{entity['id']:03d}.md").write_text(
            render_iter_md(entity, content)
        )

    def add_plan_item(self, sketch: str, type: str = "execution", tag: str = "committed") -> PlanItem:
        """Append a new plan item to state.plan. Returns the new item."""
        existing = self._state.get("plan", [])
        nums = [
            int(e["id"][1:]) for e in existing
            if isinstance(e.get("id"), str) and e["id"][1:].isdigit()
        ]
        next_num = (max(nums) + 1) if nums else 1
        item = PlanItem(id=f"P{next_num}", type=type, iter=None, tag=tag, sketch=sketch)
        self._state["plan"].append(item.to_entity())
        self._save_state()
        return item

    def link_plan_item(self, plan_id: str, iter_id: int) -> PlanItem:
        """Set the iter field of a plan item. Raises GateError if not found."""
        for entity in self._state.get("plan", []):
            if entity["id"] == plan_id:
                entity["iter"] = iter_id
                self._save_state()
                return PlanItem.from_entity(entity)
        raise GateError(f"plan item '{plan_id}' not found.")

    def record_snapshot(self) -> Path:
        """Regenerate snapshot.md and plan.md derived views from state."""
        snap = self._path / "snapshot.md"
        existing = snap.read_text() if snap.is_file() else f"# {self.name} - snapshot\n"
        iterations = self.iterations()
        snap.write_text(
            build_snapshot(
                existing,
                iterations,
                self._clock.today().isoformat(),
                plan_items=self.plan_items(),
            )
        )
        self._render_plan()
        return snap

    def open_iteration(self, title: str, type: str = DEFAULT_TYPE) -> Iteration:
        """Create the next iteration at phase 'proposed', then refresh snapshot.md.

        Gate: refuse unless the latest iteration is accepted (none = first open).
        Type must be one of TYPES. State is updated first; markdown views follow.
        """
        if type not in TYPES:
            raise GateError(
                f"unknown iteration type '{type}'. Allowed: {', '.join(TYPES)}."
            )
        latest = self.current_iteration()
        if latest is not None and not latest.is_accepted:
            raise GateError(
                f"cannot open - iteration {latest.id:03d} is phase '{latest.phase}', "
                f"not '{OPENABLE_AFTER}'. Accept (or reject -> redo -> accept) it first."
            )
        ids = self.iteration_ids()
        next_id = (max(ids) + 1) if ids else 1
        iteration = Iteration.new(
            id=next_id, title=title, opened=self._clock.today().isoformat(), type=type
        )
        entity = iteration.to_entity()
        content = {
            "id": next_id,
            "dod": {"preamble": "", "items": parse_dod_items(SKELETONS.get(type, SKELETONS[DEFAULT_TYPE]))},
            "self_review": None,
            "handback": None,
        }
        # State first.
        self._state["iterations"].append(entity)
        self._save_state()
        # Views second.
        self.iterations_dir.mkdir(exist_ok=True)
        self._save_iter_content(next_id, content)
        self._render_iter(entity, content)
        self.record_snapshot()
        return iteration

    def transition(self, verb: str, note: str | None = None) -> Iteration:
        """Apply a named phase transition to the current iteration.

        Validates the move against the transition table. State is updated first;
        markdown views (NNN.md frontmatter + body, snapshot.md) follow.
        """
        if verb not in TRANSITIONS:
            raise GateError(f"unknown transition '{verb}'.")
        iteration = self.current_iteration()
        if iteration is None:
            raise GateError("no iteration to transition.")
        source, target = TRANSITIONS[verb]
        if iteration.phase != source:
            raise GateError(
                f"cannot {verb} - iteration {iteration.id:03d} is phase "
                f"'{iteration.phase}', not '{source}'."
            )
        # Mutate state.
        entity = self._state["iterations"][-1]
        entity["phase"] = target
        if verb in VERDICT_LABELS:
            stamp = {
                "date": self._clock.today().isoformat(),
                "verdict": VERDICT_LABELS[verb].lower(),
                "reason": note.strip() if verb == "reject" and note and note.strip() else None,
            }
            entity["verdicts"].append(stamp)
        # State first.
        self._save_state()
        # Regenerate NNN.md view from NNN.json content + updated state entity.
        content = self._load_iter_content(iteration.id)
        self._render_iter(entity, content)
        self.record_snapshot()
        return Iteration.from_entity(entity)
