"""The Workstream model: a directory of objective + snapshot + iterations.

Owns the deterministic control logic for the loop. After P5, state.json is the
source of truth for workstream status and iterations; markdown files are views
regenerated by the engine. The Clock is injected so the `opened` date is
deterministic and tests need no real wall-clock.
"""
from __future__ import annotations

from pathlib import Path

from .clock import Clock
from .errors import GateError
from .iteration import (
    DEFAULT_TYPE,
    Iteration,
    OPENABLE_AFTER,
    SKELETONS,
    TRANSITIONS,
    TYPES,
    VERDICT_LABELS,
    parse_dod_items,
)
from .plan import PlanItem
from .snapshot import build_snapshot

# Lifecycle state of a whole workstream, held in state.json (view: objective.md).
ACTIVE = "active"
CLOSED = "closed"


class Workstream:
    def __init__(self, store, id: str, slug: str, clock: Clock, state_doc: dict) -> None:
        self._store = store
        self._id = id
        self._slug = slug
        self._clock = clock
        self._state = state_doc

    @classmethod
    def on_filesystem(cls, ws_dir: Path, clock: Clock, state_doc: dict) -> "Workstream":
        """Build a filesystem-backed Workstream from its directory.

        Convenience for callers/tests that hold a workstream dir rather than a
        store + slug; roots a FilesystemStore at the dir's parent. Supports both
        NNNN-slug folder names (id=NNNN, slug=slug) and plain-slug names (id=slug).
        """
        from .store import FilesystemStore, _folder_id, _folder_slug
        store = FilesystemStore.from_workstreams_root(ws_dir.parent)
        id = _folder_id(ws_dir.name)
        slug = _folder_slug(ws_dir.name)
        return cls(store, id, slug, clock, state_doc)

    @property
    def id(self) -> str:
        return self._id

    @property
    def name(self) -> str:
        return self._slug

    @property
    def state_doc(self) -> dict:
        """The in-memory state document. Read-only by convention."""
        return self._state

    @property
    def status(self) -> str:
        """`active` or `closed`. Read from state.json."""
        return self._state["workstream"].get("status", ACTIVE)

    @property
    def is_closed(self) -> bool:
        return self.status == CLOSED

    def _load_objective(self) -> dict:
        from .validate import validate_entity
        doc = self._store.read(self._id, "objective")
        validate_entity("objective", doc)
        return doc

    def _save_objective(self, doc: dict) -> None:
        from .validate import validate_entity
        validate_entity("objective", doc)
        self._store.write(self._id, "objective", doc)

    def set_status(self, status: str) -> None:
        """Update workstream status in state.json and objective.json (JSON-only)."""
        self._state["workstream"]["status"] = status
        self._save_state()
        obj = self._load_objective()
        obj["status"] = status
        self._save_objective(obj)

    def objective_line(self) -> str:
        """Workstream title from state — no disk read required."""
        return self._state["workstream"].get("title", "(empty objective)")

    def derive_snapshot(self) -> str:
        """The Done/Now/Next snapshot derived from state in-memory (never persisted)."""
        return build_snapshot(
            f"# {self.name} - snapshot\n",
            self.iterations(),
            self._clock.today().isoformat(),
            plan_items=self.plan_items(),
        )

    def snapshot_done_now_next(self) -> str:
        """Slice of the derived snapshot from the first `## Done` to EOF."""
        lines = self.derive_snapshot().splitlines()
        for i, line in enumerate(lines):
            if line.strip().lower().startswith("## done"):
                return "\n".join(lines[i:]).rstrip()
        return self.derive_snapshot().rstrip()

    def iteration_ids(self) -> list[int]:
        return [e["id"] for e in self._state["iterations"]]

    def iterations(self) -> list[Iteration]:
        """Every iteration, oldest first — built from state.json."""
        return [Iteration.from_entity(e) for e in self._state["iterations"]]

    def current_iteration(self) -> Iteration | None:
        if not self._state["iterations"]:
            return None
        return Iteration.from_entity(self._state["iterations"][-1])

    def plan_items(self) -> list[PlanItem] | None:
        """Plan items from state.json.

        Returns None when state.plan is empty — signals build_snapshot to
        preserve the hand-authored Next section rather than derive one.
        Returns a non-empty list when plan items exist.
        """
        items = self._state.get("plan", [])
        if not items:
            return None
        return [PlanItem.from_entity(e) for e in items]

    def _save_state(self) -> None:
        """Validate + persist state through the store (JSON-only; no derived views)."""
        self._store.write(self._id, "state", self._state)

    def _save_iter_content(self, iter_id: int, content: dict) -> None:
        from .validate import validate_entity
        validate_entity("iteration_content", content)
        self._store.write(self._id, f"iteration:{iter_id:03d}", content)

    def add_plan_item(self, sketch: str, type: str = "execution", tag: str = "committed") -> PlanItem:
        """Append a new plan item to state.plan. Returns the new item."""
        existing = self._state.get("plan", [])
        nums = [
            int(e["id"][1:]) for e in existing
            if isinstance(e.get("id"), str) and e["id"][1:].isdigit()
        ]
        next_num = (max(nums) + 1) if nums else 1
        item = PlanItem(id=f"P{next_num}", type=type, iter=None, tag=tag, sketch=sketch)
        self._state["plan"].append(item.to_entity())
        self._save_state()
        return item

    def link_plan_item(self, plan_id: str, iter_id: int) -> PlanItem:
        """Set the iter field of a plan item. Raises GateError if not found."""
        for entity in self._state.get("plan", []):
            if entity["id"] == plan_id:
                entity["iter"] = iter_id
                self._save_state()
                return PlanItem.from_entity(entity)
        raise GateError(f"plan item '{plan_id}' not found.")


    def open_iteration(self, title: str, type: str = DEFAULT_TYPE) -> Iteration:
        """Create the next iteration at phase 'proposed', then refresh snapshot.md.

        Gate: refuse unless the latest iteration is accepted (none = first open).
        Type must be one of TYPES. State is updated first; markdown views follow.
        """
        if type not in TYPES:
            raise GateError(
                f"unknown iteration type '{type}'. Allowed: {', '.join(TYPES)}."
            )
        latest = self.current_iteration()
        if latest is not None and not latest.is_accepted:
            raise GateError(
                f"cannot open - iteration {latest.id:03d} is phase '{latest.phase}', "
                f"not '{OPENABLE_AFTER}'. Accept (or reject -> redo -> accept) it first."
            )
        ids = self.iteration_ids()
        next_id = (max(ids) + 1) if ids else 1
        iteration = Iteration.new(
            id=next_id, title=title, opened=self._clock.today().isoformat(), type=type
        )
        entity = iteration.to_entity()
        content = {
            "id": next_id,
            "dod": {"preamble": "", "items": parse_dod_items(SKELETONS.get(type, SKELETONS[DEFAULT_TYPE]))},
            "self_review": None,
            "handback": None,
        }
        # State first, then the iteration content doc (JSON-only).
        self._state["iterations"].append(entity)
        self._save_state()
        self._save_iter_content(next_id, content)
        return iteration

    def _save_decisions(self, doc: dict) -> None:
        from .validate import validate_entity
        validate_entity("decisions", doc)
        self._store.write(self._id, "decisions", doc)

    def add_decision(self, decision: str, context: str = "", rationale: str = "") -> dict:
        """Append a decision entry to the decisions artifact (JSON-only)."""
        doc = self._store.read(self._id, "decisions") or {"entries": []}
        entry = {
            "date": self._clock.today().isoformat(),
            "context": context.strip(),
            "decision": decision.strip(),
            "rationale": rationale.strip(),
        }
        doc["entries"].append(entry)
        self._save_decisions(doc)
        return entry

    def save_retro(self, retro: dict) -> None:
        """Validate + persist the retro artifact through the store (JSON-only)."""
        from .validate import validate_entity
        validate_entity("retro", retro)
        self._store.write(self._id, "retro", retro)

    def retro_doc(self) -> dict | None:
        """The retro artifact through the store, or None if not yet written."""
        return self._store.read(self._id, "retro")

    def transition(self, verb: str, note: str | None = None) -> Iteration:
        """Apply a named phase transition to the current iteration.

        Validates the move against the transition table. State is the only
        artifact mutated (JSON-only; no derived markdown views).
        """
        if verb not in TRANSITIONS:
            raise GateError(f"unknown transition '{verb}'.")
        iteration = self.current_iteration()
        if iteration is None:
            raise GateError("no iteration to transition.")
        source, target = TRANSITIONS[verb]
        if iteration.phase != source:
            raise GateError(
                f"cannot {verb} - iteration {iteration.id:03d} is phase "
                f"'{iteration.phase}', not '{source}'."
            )
        # Mutate state.
        entity = self._state["iterations"][-1]
        entity["phase"] = target
        if verb in VERDICT_LABELS:
            stamp = {
                "date": self._clock.today().isoformat(),
                "verdict": VERDICT_LABELS[verb].lower(),
                "reason": note.strip() if verb == "reject" and note and note.strip() else None,
            }
            entity["verdicts"].append(stamp)
        self._save_state()
        return Iteration.from_entity(entity)
